
version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ../db/init.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - "5432:5432"
    restart: unless-stopped
  minio:
    container_name: minio_container
    image: bitnami/minio:latest
    environment:
      MINIO_ACCESS_KEY: 'access'
      MINIO_SECRET_KEY: 'superSecretPassword'
    ports:
      - "9001:9001"
      - "9000:9000"
    restart: unless-stopped


networks:
  postgres:
    driver: bridge