
version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ../db/init.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  minio:
    container_name: minio_container
    image: minio/minio
    networks:
      - postgres


networks:
  postgres:
    driver: bridge